# Generated by Django 6.0 on 2025-12-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_id', models.BigIntegerField()),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('subject', models.TextField(blank=True, default='')),
                ('body', models.TextField(blank=True, default='')),
                ('bedrock_json', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GmailState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_history_id', models.BigIntegerField(default=2377)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
